

# This file was *autogenerated* from the file 2_pow_128.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_128 = Integer(128)
print("2 ^ 128 =", _sage_const_2  ** _sage_const_128 ) # 340282366920938463463374607431768211456

