

# This file was *autogenerated* from the file g_multiples.sage
from sage.all_cmdline import *   # import sage library

_sage_const_21888242871839275222246405745257275088696311157297823662689037894645226208583 = Integer(21888242871839275222246405745257275088696311157297823662689037894645226208583); _sage_const_21888242871839275222246405745257275088548364400416034343698204186575808495617 = Integer(21888242871839275222246405745257275088548364400416034343698204186575808495617); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_9 = Integer(9)# BN254 base field
p = _sage_const_21888242871839275222246405745257275088696311157297823662689037894645226208583 
Fp = GF(p)

# BN254 scalar field
q = _sage_const_21888242871839275222246405745257275088548364400416034343698204186575808495617 
Fq = GF(q)

a = Fp(_sage_const_0 )
b = Fp(_sage_const_3 )
E = EllipticCurve(Fp, (a, b))
G = E(_sage_const_1 , _sage_const_2 )  # Generator
E.set_order(q)

q_bitlength = q.nbits()
nbits = (q_bitlength >> _sage_const_2 ) + _sage_const_9 
multiplicator = _sage_const_2  ** (nbits - _sage_const_1 )

result = G * multiplicator

x, y = result.xy()
print("x =", int(x))
print("y =", int(y))

