[package]
name = "zk_evm"
version = "0.131.0-rc.2"
edition = "2021"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/era-zk_evm"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
description = "ZKsync out-of-circuit EraEVM implementation"

resolver = "2"

[dependencies]
zkevm_opcode_defs = { version = "=0.131.0", path = "../zkevm_opcode_defs" }

serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
num = { version = "0.4"}
sha3 = { package = "sha3_ce", version = "=0.10.6" }
sha2 = { package = "sha2_ce", version = "=0.10.6" }
blake2 = { package = "blake2_ce", version = "=0.10.6" }
k256 = { version = "0.11", features = ["arithmetic", "ecdsa"] }
static_assertions = "1"
lazy_static = "1.4"

[dev-dependencies]
hex = "0.4"

[features]
